kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mssql-disk
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: zeroedthick
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: mssql-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi